#!/bin/bash

# Deploy blue and green versions
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
kubectl apply -f kubeservice.yaml

# Check pods
kubectl get pods

# Check logs for green deployment
GREEN_POD=$(kubectl get pods -l app=messaging-app-green -o jsonpath='{.items[0].metadata.name}')
echo "Logs for green deployment pod: $GREEN_POD"
kubectl logs $GREEN_POD
