apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  type: ClusterIP
  selector:
    app: messaging-app-blue  # Start by routing to blue deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
# To switch to green, change selector to app: messaging-app-green
